'''d={}
name=input("Enter Name:")
adddr=input('Enter Address:')
d[name]=adddr
print(d)'''

#help('modules')
'''import cx_Oracle
cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
con=cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
cursor = con.cursor()
query = "CREATE TABLE persons(person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,first_name VARCHAR2(50) NOT NULL,   last_name VARCHAR2(50) NOT NULL,    PRIMARY KEY(person_id))"
cursor.execute(query)
con.commit()'''

#oracle:
#Write a program to connect with oracle database and print the version:
'''import cx_Oracle
cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
con=cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
if con!=None:
    print("conneted successfully")
    print('version:',con.version)
else:
    print("Connection failed")'''

#Write a program to create Employees table with name:Employees(eno,ename,esal,eaddr)
'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con=cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    query="create table employees(eno number,ename varchar2(10),esal number(10,2),eaddr varchar2(10))"
    cursor=con.cursor()
    cursor.execute(query)
    print('Table created successfully')
except cx_Oracle.DatabaseError as e:
    print("There is problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''
#To insert data into tables:
'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    query="insert into employees values(100,'Harika',1000,'HYD')"
    cursor=con.cursor()
    cursor.execute(query)
    con.commit()
    print('Record inserted sucessfully')
except cx_Oracle.DatabaseError as e:
    print("There is problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''
#program to insert multiple rows into a table by using exectemany() method:

'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    query="insert into employees values(:eno,:ename,:esal,:eaddr)"
    records=[(200,'Ganesh',2000,'Canada'),(300,'Ruthu',4000,'CAnada'),(400,'Tinku',5000,'HYD')]
    cursor=con.cursor()
    cursor.executemany(query,records)
    con.commit()
    print("Records inserted sucessfully")
except cx_Oracle.DatabaseError as e:
    print("There is problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''

#write a program to insert multiple rows into a table with dynamically typed through keyboard:

'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    while True:
        eno=int(input("Enter Emp no:"))
        ename=input("enter emp name:")
        esal=float(input("Enter emp sal:"))
        eaddr=input("Enter emp address:")
        qurey="insert into employees values(%d,'%s',%f,'%s')"
        cursor.execute(qurey %(eno,ename,esal,eaddr))
        print("Insert Record sucessfully")
        option=input("Do u want to enter one more record[yes/no]:")
        if option=='no':
            con.commit()
            break
except cx_Oracle.DatabaseError as e:
    print("There is problem in db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''

#write a program to update emp salary with increment by 1000 whose salary is less than 5000
'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    increment=float(input("Enter increment value:"))
    salrange=float(input("Enter salary range:"))
    query="update employees set esal=esal+%f where esal<%f"
    cursor.execute(query %(increment,salrange))
    con.commit()
    print('Salary updated successfully')
except cx_Oracle.DatabaseError as e:
    print("There is a problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''

#progrm to delete employess whose sal is >than cutoff:

'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    cutoff=float(input("Enter cutoff salary:"))
    query="delete from employees where esal>%f"
    cursor.execute(query %cutoff)
    con.commit()
    print("Update successfully")
except cx_Oracle.DatabaseError as e:
    print("There is a problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''


'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    cutoff=float(input("Enter cutoff salary:"))
    salrange=float(input("Enter salary range:"))
    query="update employees set esal=esal-%f where esal>%f"
    cursor.execute(query %(cutoff,salrange))
    con.commit()
    print("Update successfully")
except cx_Oracle.DatabaseError as e:
    print("There is a problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''

#write a program to select all employees info by using fetchone() method:
'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    query="select * from employees"
    cursor.execute(query)
    row=cursor.fetchone()
    while row!=None:
        print(row)
        row=cursor.fetchone()
except cx_Oracle.DatabaseError as e:
    if con:
        con.rollback()
        print("There is a problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''

#fetchall():
'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    query="select * from employees"
    cursor.execute(query)
    data=cursor.fetchall()
    for row in data:
        print("Employee No:",row[0])
        print("Employee Name:", row[1])
        print("Employee salary:", row[2])
        print("Employee Address:", row[3])
        print()
        print()
except cx_Oracle.DatabaseError as e:
    if con:
        con.rollback()
        print("There is a problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''
#fetchmany(n):
'''import cx_Oracle
try:
    cx_Oracle.init_oracle_client("D:\drivers\instantclient_21_7")
    con = cx_Oracle.connect("dbaharika/harika1990@localhost:1521/orcl")
    cursor=con.cursor()
    query="select * from employees"
    cursor.execute(query)
    n=int(input("Enter No Of employees info Required:"))
    data=cursor.fetchmany(n)
    for row in data:
        print("Employee Number:",row[0])
        print("Employee Name:",row[1])
        print("Employee salary:",row[2])
        print("Employee Address:",row[3])
        print()
except cx_Oracle.DatabaseError as e:
    if con:
        con.rollback()
        print("There is problem with db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''


'''l1=[10,20,30,40,50]
l2=l1.copy()
l1[2]=99
print('l1:',l1)
print('l2:',l2)'''
'''import copy
l1=[10,20,[30,40],50]
l2=copy.copy(l1)
l1[2][0]=888
print('l1:',l1)
print('l2:',l2)'''

'''import copy
l1=[10,20,30,40,50]
l2=copy.copy(l1)
l1[2]=888
print('l1:',l1)
print('l2:',l2)'''

'''import copy
l1=[10,20,[30,40],50]
l2=copy.copy(l1)
l1[0]=111
l1[2][0]=999
print('l1:',l1)
print('l2:',l2)'''

'''import copy
l1=[10,20,[30,40],50]
l2=copy.deepcopy(l1)
l1[0]=111
l1[1]=222
l1[2][0]=888
l1[2][1]=999
l1[3]=777
print('l1:',l1)
print('l2:',l2)'''

'''l1=[10,20,[30,40],50]
l2=l1.copy()
l1[0]=111
l1[1]=222
l1[2][0]=888
l1[2][1]=999
l1[3]=777
print('l1:',l1)
print('l2:',l2)'''

#help('modules')
#write a program to insert data into database and retrive data from the database by using mysql:

'''import pymysql
try:
    con=pymysql.connect(host='localhost',database='harikadb',user='dbaharika',password='harika1990')
    cursor=con.cursor()
    #cursor.execute("create table employees1(eno int(5) primary key,ename varchar(10),esal double(10,2),eaddr varchar(10))")
    #print("Table created...")
    query="""INSERT INTO employees1 (eno, ename, esal, eaddr) 
                                VALUES (%s, %s, %s, %s) """
    record=[(111,'Kathrina',1111,'Mumbai'),(222,'Karinna',2222,'Mumbai'),(333,'Deepika',3333,'Delhi')]
    cursor.execute(query,record)
    con.commit()
    print("Record inserted successfully")
    cursor.executemany("select * from employees1")
    data=cursor.fetchall()
    for row in data:
        print("Emp Num:",row[0])
        print("Emp Name:", row[1])
        print("Emp salary:", row[2])
        print("Emp Address:", row[3])
        print()
except pymysql.DatabaseError as e:
    if con:
        con.rollback()
        print("there is a problem in db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''


'''import pymysql
try:
    con=pymysql.connect(host='localhost',database='harikadb',user='dbaharika',password='harika1990')
    cursor=con.cursor()
    cursor.execute("create table employees2(eno int(5) primary key,ename varchar(10),esal double(10,2),eaddr varchar(10))")
    print("Table created...")

except pymysql.DatabaseError as e:
    if con:
        con.rollback()
        print("there is a problem in db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close()'''


import pymysql
try:
    con=pymysql.connect(host='localhost',database='harikadb',user='dbaharika',password='harika1990')
    cursor=con.cursor()
    query="""INSERT INTO employees1 (eno,ename,esal,eaddr) 
                                VALUES (%s,%s,%s,%s) """
    rows=[(110,'Kathrina',1111,'Mumbai'),(220,'Karinna',2222,'Mumbai'),(330,'Deepika',3333,'Delhi')]
    for row in rows:
        cursor.execute(query, row)
    con.commit()
    print("Record inserted successfully")

except pymysql.DatabaseError as e:
    if con:
        con.rollback()
        print("there is a problem in db:",e)
finally:
    if cursor:
        cursor.close()
    if con:
        con.close




